class CookiecutterException(Exception): ...
class InvalidConfiguration(Exception): ...
class UndefinedVariableInTemplate(Exception): ...
class ContextDecodingException(Exception): ...
class NonTemplatedInputDirException(Exception): ...
