# output-format: json

strictness: high
test-warnings: true
doc-warnings: false
member-warnings: false
inherits:
  - default
ignore-paths:
  - docs
ignore-patterns:
  - (^|/)skip(this)?(/|$)
  - tests/test_commands.py
  - tests/test_mediator.py
  - tests/test_notification.py
  - tests/test_phi.py
autodetect: false
max-line-length: 120


pyflakes:
  run: true
  disable:
    - F403
    - F810

pyroma:
  run: true
  disable:
    - PYR15
    - PYR18

dodgy:
  run: true

mccabe:
  run: true
  options:
    max-complexity: 12

pylint:
  run: false

bandit:
  run: false
  options:
    config: bandit.yml

frosted:
  run: false
  disable:
    - E103
    - E306

pep8:
  run: false
  disable:
    - W602
    - W603
  enable:
    - W601
  options:
    max-line-length: 79

pep257:
  run: false
  disable:
    - D100
    - D101

mypy:
  run: false
  options:
    ignore-missing-imports: true
    follow-imports: skip

vulture:
  run: false
