## Codecov Upload - Reusable Workflow ##

on:
  workflow_call:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Codecov binary
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov

      # DOWNLOAD XML FILES FROM ARTIFACTS
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: coverage
          pattern: coverage-*
          merge-multiple: true

      - run: ls -R coverage

      # UPLOAD XML FILES TO CODECOV
      - name: Upload Coverage Reports to Codecov
        run: |
          for file in coverage/coverage*.xml; do
            OS_NAME=$(echo $file | sed -E "s/coverage-(\w\+)-/\1/")
            PY_VERSION=$(echo $file | sed -E "s/coverage-\w\+-(\d\.)\+/\1/")
            ./codecov -f $file -e "OS=$OS_NAME,PYTHON=$PY_VERSION" --flags unittests --verbose
            echo "[INFO] Sent to Codecov: $file !"
          done
