name: "Pull Request Labeler"

on:
  - pull_request_target

jobs:
  label_PR:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5

      # PR targeting 'boarding-auto' branch, needs to run CI Tests, given labels
      ######## Merge ########
      - name: "Merge PR, Signaling what Automated Tests to run"
        if:  startsWith(github.head_ref, 'boarding-auto')
        run: gh pr merge ${{ github.event.number }} --auto
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: "Label PR with 'boarding-auto' label"
        if: github.event_name == 'pull_request_target' && contains(github.event.pull_request.base.ref, 'boarding-auto')
        run: gh pr edit ${{ github.event.number }} --add-label 'boarding-auto'
