#############################
## PR to Boarding - GitOps ##
#############################

# export tt='board-request'; git tag -d "$tt"; git push --delete origin "$tt"; git tag "$tt" && git push origin "$tt"

on:
  push:
    tags:
      - board-request

jobs:
  pr_to_boarding:
    uses: boromir674/automated-workflows/.github/workflows/go-pr-to-boarding.yml@test
    with:
      boarding_branch: ${{ vars.BOARDING_BRANCH || 'boarding-auto' }}
      main_branch: ${{ vars.MAIN_BRANCH || 'master' }}
    secrets:
      github_pat: ${{ secrets.GH_TOKEN }}
