############################
## Request to Board Train ##
############################

# export tt='board-request'; git tag -d "$tt"; git push --delete origin "$tt"; git tag "$tt" && git push origin "$tt"

on:
  push:
    tags:
      - board-request

jobs:
  boarding_area:
    runs-on: ubuntu-latest
    env:
      BOARDING_BR: 'boarding-auto'
      MAIN_BR: 'master'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 0 indicates all history for all branches and tags.
          set-safe-directory: ''  # `git config --global --add safe.directory <path>`
          # GH_TOKEN should be a PAT, that allows to trigger Actions Workflow (default GITHUB_TOKEN cannot invoke Worklflows!)
          token: '${{ secrets.GH_TOKEN }}'

      # Find Upstream Branch, pointing to the same commit as the Pushed Tag
      - name: Discover User's Branch Name
        id: user_branch
        run: |
          name=$(git branch -a --contains "$(git rev-parse HEAD)" | sed -n '2p' | sed 's/.*origin\///')
          echo "NAME:" $name
          echo USER_BRANCH=$name >> $GITHUB_OUTPUT

      - name: "Exit Job, if User Branch is empty: '${{ steps.user_branch.outputs.USER_BRANCH }}'"
        if: steps.user_branch.outputs.USER_BRANCH == ''
        run: echo "[ERROR] User Branch not found. Searched for an Upstream branch, but was not found on the remote. Exiting.." && exit 1

      ### Put User Branch on Boarding Branch to Test before merging to Release Train
      # Create Upstream 'Boarding' Branch
      - run: git checkout ${{ env.MAIN_BR }}
      - run: git branch --track "origin/${{ env.BOARDING_BR }}" || echo "Remote Branch '${{ env.BOARDING_BR }}' does not exist"
      - run: git checkout -b ${{ env.BOARDING_BR }} || git checkout ${{ env.BOARDING_BR }}
      - run: git rebase ${{ env.MAIN_BR }}
      - run: git push -u origin ${{ env.BOARDING_BR }}

      - run: git checkout ${{ steps.user_branch.outputs.USER_BRANCH }}
      - run: git rebase ${{ env.BOARDING_BR }}
      - run: git push -u origin ${{ steps.user_branch.outputs.USER_BRANCH }}

      - run: git config --global user.email "k.lampridis@hotmail.com"
      - run: git config --global user.name "Konstantinos Lampridis"

      ############## PR ##############
      - name: 'Open PR ${{ steps.user_branch.outputs.USER_BRANCH }}  -->  ${{ env.BOARDING_BR }}, to classify file changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh pr create --head "${{ steps.user_branch.outputs.USER_BRANCH }}" --base "${{ env.BOARDING_BR }}" \
            --title "Boarding Area: Merging '${{ steps.user_branch.outputs.USER_BRANCH }}' into '${{ env.BOARDING_BR }}' Branch" \
            --body "## :train: Boarding Area :train:

          This PR is automatically generated by a GitHub Action workflow. It's part of the process of putting changes onto the **Boarding Auto** branch, setting the stage for the next steps in our GitOps journey.

          ### What's Happening Here?

          - We're merging changes from `${{ steps.user_branch.outputs.USER_BRANCH }}` into the `${{ env.BOARDING_BR }}` branch.
          - The PR is automatically labeled and classified, to help us understand the nature of the changes.
          - The labels applied to this PR, signal what Automated Tests to run as Check before Mering into the Release Train.

          ### Type of Changes

          - Source Distribution
          - Documentation

          ### :white_check_mark: Automatic Merging :white_check_mark:

          - This PR is designed to **automatically merge** once all CI checks pass.
          "
