################################
## Docs Readme Publish ##
##     Reusable Workflow      ##
################################

# 1. Gets state on tagged commit
# 2. creates an empemeral branch
# 3. pushes the empemeral branch to GitHub
# 4. creates a PR from empemeral branch to docs-auto branch
# 5. merges the PR into docs-auto branch, on successful Docs Build
# 6.  Deletes the empemeral branch

###### Quick Release Tagging #######
# export tt='quick-release'; git tag -d "$tt"; git push --delete origin "$tt"; git tag "$tt" && git push origin "$tt"
##############   OR   ##############
# export tt='quick-release'
# git tag -d "$tt"
# git push --delete origin "$tt"
# git tag "$tt"
# git push origin "$tt"
####################################

# PR: empemeral-doc-updates --> docs-auto

# Trigger only on push of a 'quick-release' tag, on any branch
on:
  # on tag with name 'quick-release' only
  push:
    tags:
      - quick-release


jobs:
  release_readme:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Add repository path as safe.directory for Git global config by running `git
          # config --global --add safe.directory <path>`
          # Default: true
          set-safe-directory: ''

      # pushed tag that we checkout is not a branch, so we need to create a branch

      - run: git checkout -b empemeral-doc-updates
      - run: git push -u origin HEAD

      - name: Create Pull Request
        # --head is the branch where the changes were developed
        # --base is the branch you want to merge the changes into
        run: |
          gh pr create --head empemeral-doc-updates --base docs-auto  \
            --title "Documentation Updates - Merge to Dedicated Branch" \
            --body "This PR is automatically generated by a GitHub Action workflow. \
            It contains documentation updates that were pushed to the 'quick-release' tag. \
            The workflow will merge this PR into the 'docs-auto' branch, which will \
            trigger a new build of the documentation site. \
            \n\n\
            Please do not close this PR manually."

      - name: 'Merge Pull Request into docs-auto and delete empemeral-doc-updates Branch'

      # gh pr merge          :  If required checks have not yet passed, AutoMerge will be enabled.

      #   --auto             :  Automatically merge only after necessary requirements are met
      #   -s, --squash       :  Squash the commits into one commit and merge it into the base branch
      #   -d, --delete-branch:  Delete the local and remote branch after merge

        run: |
          gh pr merge empemeral-doc-updates --auto --delete-branch --squash
